server:
  port: 8080

spring:
  application:
    name: ms.product

  profiles:
    active: ${ACTIVE_PROFILE:local}

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #  datasource:
  #    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  #    url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres}
  #    username: ${DB_USERNAME:postgres}
  #    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
        liquibase-schema: public

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    default-schema: public
    enabled: true

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms
          max-interval: 5000ms
          multiplier: 1
          max-retries: 5
        missing-queues-fatal: false

rabbitmq:
  queue:
    product-approved: PRODUCT_APPROVED_QUEUE
    product-approved-dlq: PRODUCT_APPROVED_QUEUE_DLQ
    product-rejected: PRODUCT_REJECTED_QUEUE
    product-rejected-dlq: PRODUCT_REJECTED_QUEUE_DLQ
    product-created: PRODUCT_CREATED_QUEUE
    product-created-dlq: PRODUCT_CREATED_QUEUE_DLQ